// Note: Open-Meteo uses numeric weather codes
export const weatherMap: Record<number, string> = {
  0: "Clear",
  1: "Mainly clear",
  2: "Partly cloudy",
  3: "Overcast",
  45: "Fog",
  48: "Rime Fog",
  51: "Light Drizzle",
  52: "Moderate Drizzle",
  53: "Dense Drizzle",
  56: "Light Freezing Drizzle",
  57: "Dense Freezing Drizzle",
  61: "Rain",
  63: "Moderate Rain",
  65: "Heavy Rain",
  66: "Freezing Rain",
  67: "Heavy Freezing Rain",
  71: "Snow",
  73: "Moderate Snow",
  75: "Heavy Snow",
  77: "Snow Grains",
  80: "Rain Showers",
  81: "Moderate Rain Showers",
  82: "Violent Rain Showers",
  85: "Snow Showers",
  86: "Heavy Snow Showers",
  95: "Thunderstorm",
  96: "Thunderstorm with hail",
  99: "Thunderstorm with heavy hail",
};

// Day icons
export const iconMapDay: Record<number, string> = {
  0: "☀️",
  1: "🌤️",
  2: "⛅",
  3: "☁️",
  45: "🌫️",
  48: "🌫️",
  51: "🌦️",
  52: "🌦️",
  53: "🌦️",
  56: "🌧️",
  57: "🌧️",
  61: "🌧️",
  63: "🌧️",
  65: "🌧️",
  66: "🌧️",
  67: "🌧️",
  71: "❄️",
  73: "❄️",
  75: "❄️",
  77: "❄️",
  80: "🌦️",
  81: "🌦️",
  82: "🌦️",
  85: "🌨️",
  86: "🌨️",
  95: "⛈️",
  96: "⛈️",
  99: "⛈️",
};

// Night icons
export const iconMapNight: Record<number, string> = {
  0: "🌙",
  1: "🌙",
  2: "☁️",
  3: "☁️",
  45: "🌫️",
  48: "🌫️",
  51: "🌧️",
  52: "🌧️",
  53: "🌧️",
  56: "🌧️",
  57: "🌧️",
  61: "🌧️",
  63: "🌧️",
  65: "🌧️",
  66: "🌧️",
  67: "🌧️",
  71: "❄️",
  73: "❄️",
  75: "❄️",
  77: "❄️",
  80: "🌧️",
  81: "🌧️",
  82: "🌧️",
  85: "🌨️",
  86: "🌨️",
  95: "⛈️",
  96: "⛈️",
  99: "⛈️",
};

export const getIcon = (code: number, isDay: boolean): string => {
  return isDay ? (iconMapDay[code] ?? "🌡️") : (iconMapNight[code] ?? "🌡️");
};

// Day moods
export const moodMapDay: Record<number, string> = {
  0: "Nice out, eh?",
  1: "Little chilly mate.",
  2: "Clouds trying, I guess.",
  3: "Gray vibes today.",
  45: "Lost again, classic.",
  48: "Can barely see, wow.",
  51: "Little sprinkle.",
  52: "Drizzly… yay?",
  53: "Wet shoes incoming.",
  56: "Tiny icy surprises.",
  57: "Careful, slippery out there.",
  61: "Yep… rain again.",
  63: "Boots recommended.",
  65: "Pouring, nice.",
  66: "Frozen rain? Fun.",
  67: "Slippery, watch it.",
  71: "Snow's here, enjoy.",
  73: "Moderate flakes, chill.",
  75: "Heavy snow… yikes.",
  77: "Tiny snow grains.",
  80: "Quick splash, heads up.",
  81: "Rain again, classic.",
  82: "Storm's feeling spicy.",
  85: "Snow sprinkles, hehe.",
  86: "White chaos incoming.",
  95: "Thunder rumbling… fun.",
  96: "Hail hitting, ouch.",
  99: "Big storm, careful.",
};

// Night moods
export const moodMapNight: Record<number, string> = {
  0: "Calm night, stars out.",
  1: "Night's pretty calm.",
  2: "Clouds drifting by.",
  3: "Gray night vibes.",
  45: "Foggy and quiet.",
  48: "Misty night out.",
  51: "Light drizzle, cozy.",
  52: "Drizzly night walk?",
  53: "Wet night, careful.",
  56: "Icy drizzle, yikes.",
  57: "Slippery out there.",
  61: "Rainy night.",
  63: "Good night for inside.",
  65: "Pouring, stay in.",
  66: "Frozen rain, oof.",
  67: "Slick roads tonight.",
  71: "Snow at night, magical.",
  73: "Snowfall, peaceful.",
  75: "Heavy snow, bundle up.",
  77: "Snow grains falling.",
  80: "Night showers, cozy in.",
  81: "Rainy night vibes.",
  82: "Wild night out there.",
  85: "Snowy night, nice.",
  86: "Heavy snow, stay warm.",
  95: "Thunder in the dark.",
  96: "Stormy night, careful.",
  99: "Big storm tonight.",
};

export const getMood = (code: number, isDay: boolean): string => {
  return isDay
    ? (moodMapDay[code] ?? "Mmm, just vibing.")
    : (moodMapNight[code] ?? "Quiet night out.");
};
